# frozen_string_literal: true

# this is a token generated by the lexer.
# it is read by the parser.
class LexToken

  attr_reader :content, :type

  # takes a rule and the part of the input that matched it.
  # converts the rule to a symbol, and the input to a string (if it wasnt already)
  # tokens are read-only.
  def initialize(rule_name, match_data)
    if(match_data.is_a? MatchData)
      match_data = match_data.to_s
    end

    @content = match_data
    @type = rule_name.to_sym
  end

  def to_s
    "#{@type.to_s} #{@content.to_s}"
  end
end
