# frozen_string_literal: true

require './lexeme'

# this is a lexeme generated by the lexer.
# it is read by the parser.
# it also makes up the leaves of the abstract syntax tree
class Terminal < Lexeme
  attr_reader :content, :type

  # takes a rule and the part of the input that matched it.
  # converts the rule to a symbol, and the input to a string (if it wasnt already)
  # tokens are read-only.
  def initialize(rule_name, match_data)
    super()
    match_data = match_data.to_s if match_data.is_a? MatchData

    @content = match_data
    @type = rule_name.to_sym
  end

  def to_s
    "<type: #{type}, content: #{content}>"
  end
end
